name: Build .exe file

on:
  push:
    branches:
      - master  # 或者 main，具体取决于你的主分支名称

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build .exe with pyinstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile generate_zip.py

    - name: Upload .exe file
      uses: actions/upload-artifact@v2
      with:
        name: subtitle-translator.exe
        path: dist/generate_zip.exe
